name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: cp .env.example .env

      - name: UID
        run: sed -i "s/USER_ID=1000/USER_ID=$UID/" .env

      - name: GID
        run: sed -i "s/GROUP_ID=1000/GROUP_ID=$(id |awk 'BEGIN { FS = "[=(]" } ; { print $4 }')/" .env

      - name: Create docker Network
        run: docker network create project8

      - name: Start Stack
        run: docker-compose up -d

      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Composer install
        run: docker exec project8_php composer install

      - name: Create database
        run: docker exec project8_php php bin/console --env=test doctrine:database:create

      - name: Create Schema
        run: docker exec project8_php php bin/console --env=test doctrine:schema:create

      - name: Run tests
        run: docker exec project8_php composer tests

